/**
 * Catálogo de plantillas legales chilenas que Lya puede rellenar.
 * Cada plantilla define: id, label, organismo, leyBase, placeholders requeridos
 * y un prompt-base de estructura que Lya seguirá al rellenar.
 *
 * IMPORTANTE: El contenido final lo genera el LLM con anti-alucinación
 * (verifier score). Estas plantillas son la "ficha de identidad" del documento.
 */

export const LEGAL_TEMPLATES = [
  {
    id: 'demanda_sernac',
    label: 'Demanda SERNAC',
    icon: 'Scale',
    color: 'purple',
    regulatoryBody: 'SERNAC',
    legalBase: 'Ley 19.496 sobre Protección de los Derechos de los Consumidores',
    description: 'Reclamo formal ante SERNAC por infracción a la Ley del Consumidor',
    requiredFields: ['fullName', 'rut', 'address', 'phone', 'email', 'recipient', 'factsSummary', 'amountInvolved', 'demandedAction'],
    structure: [
      'Encabezado (lugar, fecha, destinatario SERNAC región)',
      'Identificación del consumidor (nombre, RUT, domicilio, contacto)',
      'Identificación del proveedor (razón social, RUT si se conoce)',
      'Hechos (relato cronológico claro y conciso)',
      'Derecho infringido (artículos específicos Ley 19.496)',
      'Petitorio (qué solicita: devolución, reparación, multa)',
      'Documentos acompañantes',
      'Firma',
    ],
  },
  {
    id: 'recurso_reposicion_cmf',
    label: 'Recurso ante CMF',
    icon: 'Landmark',
    color: 'mint',
    regulatoryBody: 'CMF',
    legalBase: 'Ley 21.521 (Fintech) y NCG 502 CMF',
    description: 'Recurso de reposición o reclamo formal ante la Comisión para el Mercado Financiero',
    requiredFields: ['fullName', 'rut', 'address', 'recipient', 'factsSummary', 'institutionInvolved', 'demandedAction'],
    structure: [
      'Encabezado dirigido a CMF',
      'Identificación del recurrente',
      'Identificación de la institución financiera',
      'Antecedentes y hechos',
      'Fundamentos legales (Ley 21.521, NCG 502)',
      'Petitorio',
      'Firma',
    ],
  },
  {
    id: 'denuncia_csirt',
    label: 'Denuncia CSIRT',
    icon: 'ShieldAlert',
    color: 'red',
    regulatoryBody: 'CSIRT',
    legalBase: 'Ley 21.663 de Ciberseguridad',
    description: 'Reporte de incidente cibernético al CSIRT de Gobierno',
    requiredFields: ['fullName', 'rut', 'email', 'incidentType', 'incidentDate', 'factsSummary', 'evidence'],
    structure: [
      'Datos del reportante',
      'Tipo de incidente (phishing, fraude digital, suplantación)',
      'Fecha y hora del incidente',
      'Descripción técnica de los hechos',
      'Evidencias adjuntas',
      'Acciones ya tomadas',
      'Firma',
    ],
  },
  {
    id: 'carta_arco',
    label: 'Carta ARCO (Datos)',
    icon: 'FileText',
    color: 'blue',
    regulatoryBody: 'multiple',
    legalBase: 'Ley 21.719 sobre Protección de Datos Personales',
    description: 'Ejercicio de derechos ARCO (Acceso, Rectificación, Cancelación, Oposición)',
    requiredFields: ['fullName', 'rut', 'address', 'email', 'recipient', 'arcoRight', 'specificData'],
    structure: [
      'Encabezado al responsable del tratamiento de datos',
      'Identificación del titular',
      'Acreditación de identidad (copia cédula)',
      'Derecho que ejerce (Acceso/Rectificación/Cancelación/Oposición)',
      'Datos personales sobre los que se ejerce el derecho',
      'Plazo legal de respuesta (15 días hábiles)',
      'Firma',
    ],
  },
  {
    id: 'reclamo_cmf',
    label: 'Reclamo CMF',
    icon: 'Landmark',
    color: 'mint',
    regulatoryBody: 'CMF',
    legalBase: 'Ley General de Bancos · Ley 21.521',
    description: 'Reclamo contra entidad financiera ante CMF',
    requiredFields: ['fullName', 'rut', 'address', 'institutionInvolved', 'factsSummary', 'amountInvolved'],
    structure: [
      'Datos del reclamante',
      'Datos de la institución reclamada',
      'Hechos del reclamo',
      'Gestiones previas con la institución',
      'Solicitud específica',
      'Firma',
    ],
  },
  {
    id: 'denuncia_fraude_ley_20009',
    label: 'Denuncia Fraude (Ley 20.009)',
    icon: 'ShieldAlert',
    color: 'red',
    regulatoryBody: 'multiple',
    legalBase: 'Ley 20.009 sobre Limitación de Responsabilidad por Operaciones No Reconocidas',
    description: 'Denuncia formal de fraude en tarjeta o transferencia con plazo legal de 5 días',
    requiredFields: ['fullName', 'rut', 'address', 'institutionInvolved', 'factsSummary', 'amountInvolved', 'incidentDate'],
    structure: [
      'Encabezado al banco/emisor',
      'Identificación del titular',
      'Hechos del fraude (fecha, monto, tipo)',
      'Invocación Ley 20.009 (carga de la prueba en el banco)',
      'Solicitud de devolución íntegra dentro del plazo legal',
      'Documentos acompañantes',
      'Firma',
    ],
  },
  {
    id: 'recurso_proteccion',
    label: 'Recurso de Protección',
    icon: 'Scale',
    color: 'amber',
    regulatoryBody: 'tribunal',
    legalBase: 'Constitución Política · Auto Acordado Corte Suprema',
    description: 'Recurso de protección ante Corte de Apelaciones',
    requiredFields: ['fullName', 'rut', 'address', 'recipient', 'factsSummary', 'rightViolated', 'demandedAction'],
    structure: [
      'Encabezado a Iltma. Corte de Apelaciones',
      'Identificación del recurrente',
      'Identificación del recurrido',
      'Garantía constitucional vulnerada',
      'Hechos',
      'Derecho',
      'Petitorio (medidas cautelares)',
      'Firma',
    ],
  },
  {
    id: 'carta_cobro_indebido',
    label: 'Carta Cobro Indebido',
    icon: 'FileText',
    color: 'orange',
    regulatoryBody: 'SERNAC',
    legalBase: 'Ley 19.496 Art. 39 · Ley 20.555',
    description: 'Carta de reclamo por cobro indebido a entidad financiera',
    requiredFields: ['fullName', 'rut', 'address', 'institutionInvolved', 'factsSummary', 'amountInvolved'],
    structure: [
      'Encabezado al gerente de la entidad',
      'Identificación del cliente',
      'Detalle del cobro indebido',
      'Solicitud de devolución',
      'Plazo otorgado (10 días)',
      'Advertencia de denuncia SERNAC si no responde',
      'Firma',
    ],
  },
];

export function getTemplateById(id) {
  return LEGAL_TEMPLATES.find((t) => t.id === id);
}